AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for API Gateway'

Resources:
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyRESTApi

  MyApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyApiGateway.RootResourceId
      RestApiId: !Ref MyApiGateway
      PathPart: 'myresource'